In [1]:
import numpy as np

In [4]:
lst = list()
lst.extend([1,2,3,4])

In [5]:
lst

[1, 2, 3, 4]

In [6]:
arr = np.array(lst)

In [8]:
type(arr)

numpy.ndarray

In [9]:
## It is a One-Dimensional Array
arr.shape

(4,)

In [11]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
list3 = [1,4,6,7]
nd_array = np.array([list1,list2,list3])

In [12]:
nd_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 4, 6, 7]])

In [13]:
## 2-D Array with 3 rows and 4 columns
nd_array.shape

(3, 4)

In [22]:
## Reshped 3x4 array to 4x3 array (4 rows and 3 columns)
nd_array = nd_array.reshape(4,3)
nd_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [4, 6, 7]])

In [19]:
nd_array.shape

(4, 3)

## Indexing

In [24]:
## Gives all the elements in the array
nd_array[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [4, 6, 7]])

In [25]:
## The first (0:2) tells that I need row elements in 0 to 2nd row
## The second (0:2) tells that I need column elements in 0 to 2nd column
nd_array[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [26]:
##If I need to get [[1,2,3],[4,5,6]]
nd_array[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
## If I need to get [[1,2],[4,5],[7,8]]
nd_array[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [36]:
## np.arange(start,stop,step)
arr = np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [37]:
arr[3:] = 100
arr

array([  0,   2,   4, 100, 100])

In [42]:
## Return evenly spaced numbers over a specified interval
## np.linspace(start,stop,number of points)
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [46]:
## In assign operation, new array will not be created. The reference will be shared. 
## To confirm this, lets change the value of the arr and check if it is reflected in arr1
arr1 = arr
## arr1 = [0,2,3,100,100]
arr[2] = 100
## arr = [0,2,100,100,100]
print(arr)
print(arr1)

[  0   2 100 100 100]
[  0   2 100 100 100]


In [49]:
## In assign operation, new array will not be created. The reference will be shared. 
## To confirm this, lets change the value of the arr and check if it is reflected in arr1
## In order to prevent this scenario, we use arr.copy function. 
## Copy function creates another memory space to store the newly created array
arr = [0,2,3,100,100]
arr1 = arr.copy()
## arr1 = [0,2,3,100,100]
arr[2] = 100
## arr = [0,2,100,100,100]
print(arr)
print(arr1)

[0, 2, 100, 100, 100]
[0, 2, 3, 100, 100]


In [53]:
## conditions in array
## <,*,/
nd_array<2

array([[ True, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

In [54]:
np.ones(4)

array([1., 1., 1., 1.])

In [55]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [56]:
## Distribute data randomly
np.random.rand(2,5)

array([[0.71551792, 0.66260427, 0.44725188, 0.93475876, 0.39812573],
       [0.00742282, 0.95557679, 0.08775562, 0.25116444, 0.34445486]])